apiVersion: apps/v1
kind: Deployment
metadata:
  name: first-app
  labels:
    group: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: first-app
  template:
    metadata:
      labels:
        app: first-app
    spec:
      containers:
        - name: first-app
          image: mmc/first-app:latest
          ports:
            - containerPort: 8888