apiVersion: v1
kind: Pod
metadata:
  name: kafka-pod
  labels:
    app: kafka
spec:
  containers:
    - name: zookeeper
      image: wurstmeister/zookeeper
    - name: kafka-contianer
      image: wurstmeister/kafka
      env:
        - name: KAFKA_PORT
          value: "9092"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "localhost:2181"
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: "localhost"
      ports:
        - containerPort: 9092
