apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka

  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: zookeeper-pod
          image: wurstmeister/zookeeper
          ports:
            - containerPort: 2181
          volumeMounts:
            - mountPath: /zookeeper
              name: shared-volume
        - name: kafka-pod
          image: wurstmeister/kafka
          env:
            - name: KAFKA_PORT
              value: "9092"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "localhost:2181"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: INSIDE:PLAINTEXT
            - name: KAFKA_ADVERTISED_LISTENERS
              value: INSIDE://localhost:9092
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: INSIDE
            - name: KAFKA_LISTENERS
              value: INSIDE://:9092
            - name: KAFKA_BROKER_ID
              value: "1"
          ports:
            - containerPort: 9092
          volumeMounts:
            - mountPath: /kafka
              name: shared-volume
      volumes: 
        - name: shared-volume
          persistentVolumeClaim:
              claimName: pvolumec
          