apiVersion: v1
kind: Service
metadata:
  name: consumer
spec:
  selector:
    app: kafka #points to template.metadata.labels deployment/pod/etc.
  ports:
    - port: 9094
      targetPort: 9094
      name: name9094

  type: LoadBalancer