apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvolume
  labels:
   name: pvolume
spec:
  capacity:
    storage: 3Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: kafka-local-storage
  local:
    path: /c/kafka
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - docker-desktop
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: pvolumec
spec:
    storageClassName: kafka-local-storage
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 1Gi
    selector:
        matchLabels:
            name: pvolume